[package]
name = "an-os"
version = "0.1.0"
authors = ["Tom Streller <tom.streller@functional-games.de>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
